site_name: Node Logic
site_url: https://www.nodelogic.au
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-48.png
  features:
    - content.code.copy
    - navigation.tabs
    
repo_url: https://github.com/nodelogicau/nodelogicau.github.io
repo_name: nodelogicau/nodelogicau.github.io
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nodelogicau
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benfortuna
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home:
    - Introduction: index.md
